[tool.poetry]
name = "petrovich"
version = "0.1.0"
description = "Чат-бот"
authors = ["AndrewSha <Xoma163rus@gmail.com>"]
readme = "README.md"
repository = "https://github.com/Xoma163/petrovich"
package-mode = false
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
beautifulsoup4 = "^4.12.3"
colorlog = "^6.8.2"
crontab = "^1.0.1"
Django = "^5.0.7"
django-environ = "^0.11.2"
django-extensions = "^3.2.3"
django-redis = "^5.4.0"
lxml = "^5.2.2"
pillow = "^10.4.0"
psycopg2 = "^2.9.9"
pydub = "^0.25.1"
python-json-logger = "^2.0.7"
requests = "^2.32.3"
twitch-dl = "^2.3.1"
uWSGI = "^2.0.26"
virtualenv = "^20.26.3"
xmltodict = "^0.13.0"
yandex-music = "^2.2.0"
yt-dlp = "^2024.7.9"
spotipy = "^2.24.0"
numpy = "^2.0.0"
python-dateutil = "^2.9.0.post0"
selenium = "^4.22.0"
sentry-sdk = { extras = ["django"], version = "^2.13.0" }
selenium-wire = "^5.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
